# see https://github.com/ankane/blazer for more info

data_sources:
  main:
    url: <%= ENV["BLAZER_DATABASE_URL"] %>

    # statement timeout, in seconds
    # none by default
    # timeout: 15

    # caching settings
    # can greatly improve speed
    # off by default
    # cache:
    #   mode: slow # or all
    #   expires_in: 60 # min
    #   slow_threshold: 15 # sec, only used in slow mode

    # wrap queries in a transaction for safety
    # not necessary if you use a read-only user
    # true by default
    # use_transaction: false

    smart_variables:
      company_id: "SELECT id, name FROM companies ORDER BY id ASC"
      period: ["day", "week", "month", "year"]
      # status: {0: "Active", 1: "Archived"}

    linked_columns:
      # user_id: "/admin/users/{value}"

    smart_columns:
      company_id: "SELECT id, name FROM companies WHERE id IN {value}"
      customer_id: "SELECT id, name FROM customers WHERE id IN {value}"
      factory_id: "SELECT id, name FROM factories WHERE id IN {value}"
      employe_id: "SELECT id, name FROM employees WHERE id IN {value}"

# create audits
audit: true
forecasting: trend

# change the time zone
# time_zone: "Pacific Time (US & Canada)"
time_zone: "Beijing"

# class name of the user model
# user_class: User

# method name for the user model
# user_name: name

# optional auth method to use as a before_action (default: nil)
# before_action: :authenticate!

# email to send checks from
# from_email: blazer@example.org

check_schedules:
  - "1 day"
  - "1 hour"
  - "5 minutes"
