# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da5aebc40440ef61db9635e1ca53f5b863a264067e5b0e85cd2960d3c7016cca966efbdd0ae1727670f1b770d5356401f910487db8878b3432207806b037d5da

test:
  secret_key_base: 6ec9d2bdc94c44827dfed61b063ba7135fa4aa29f89d179294ed65d1a5671bd50754b5d39119cd562abb584a32cd51c61e768b000ed597ff2728b414bbef7655

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
